### ISSUE TITLE
Poor responsiveness if Browse file list is sorted while still downloading

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#73] opened 2021-10-04 09:22 UTC
Obtaining a user's files can take some time if the list is particularly big or the download is slow. As such, the list of files is populated in real-time as the list downloads and more and more files are listed.

If the user clicks one of the columns causing the list to become sorted(by filename, size, etc.) while it is still downloading, the list becomes very slow and will freeze up the entire UI until the download finishes. Since this can take as long as a few minutes, MuWire remains unresponsive until this finishes.

Some solutions I can think of:

-Disable sorting by column until the file list is finished downloading.

-Run the file list tab on another thread.

-Perform file list updates periodically(ie. once per second).

Disabling sorting seems like the easiest way to go about it.

**Comment by zlatinb** [comment] 2021-10-04 10:03
I've observed this too.  Right now the UI gets updated once for every 128 results that arrive.  The easiest thing to do is to increase that value, even though it's not a real solution, just pushes the problem away.

Unfortunately the actual sorting has to happen on the UI thread, that's a constraint by the framework.  I'm not sure I can selectively disable the sorting until all results arrive, and the UI would feel broken for the user trying to sort.  

I will be looking closer into the Browse functionality as part of working on issue #65 , although my instinct tells me that a giant tree will be even slower to display than a giant table.  Or maybe not, since there is no sorting possible of the tree.

**Comment by Searinox** [comment] 2021-10-04 12:02
There are two freeze issues:

Issue 1: The updates are coming in too fast - those 128 files are coming in as 128 entry chunks. If the download is particularly fast, this results in a lot of update spam. This involves no sorting.

I think creating a queue of chunks(128 entries per chunk is fine) that is populated by the download on one end and "consumed" by the UI at regular intervals(like once or twice a second) can work. The fixed chunk size and update interval being selected as reasonable tested values that do not hold up the UI for too long.

If the download proceeds too fast, the UI will take its time populating the list at its own pace without the UI freezing. When calculating progress, the percentage should then be number of UI list entries versus total number of items according to download. Note also the need to handle stopping this if the user decides to close the Browse tab while it's still downloading/populating.

I still find the sorted grid useful and would advise having grid and tree side-by-side instead of removing the grid. That said, this technique of updating should resolve responsiveness issues just as well for both layouts!


Issue 2: This an issue that only occurs with a combination of using sorting + large number of items since everytime the list is updated with new items, it gets sorted again, and that sort has to process ALL of the items in the list. The bigger the list, the longer it takes. Eventually an update takes longer than it takes for the next 128 items to come in, resulting in being constantly stuck doing updates.

This can't be solved with what I suggested for Issue 1 because the update slowness scales with the number of items already present in the list, which only ever grows. Disabling column sort resolves this.

**Comment by zlatinb** [comment] 2021-10-04 12:45
In the commit referenced above I changed the update of the UI to happen once a second.  In my testing it is much better when a huge list of files is being browsed, even with sorting enabled (although still a bit choppy).  Please test https://muwire.com/downloads/MuWire-0.8.9-GitHub73.zip

I don't plan on removing the table view of results, user will be able to switch between Tree and Table view like in the LIbrary tab.

**Comment by Searinox** [comment] 2021-10-04 13:59
There is certainly more responsiveness. However, I did fetch the list of a user with a LOT of files and when sorted it again was lagging. The problem is that as this continues even when tabbed away to some other place in MuWire, the UI continues to freeze up.

Can you make it so that if you're tabbed away, the update event set a flag instead of updating the list, and then in the event where you tab back to the search list - if that flag was set - the list is immediately refreshed?

**Comment by zlatinb** [comment] 2021-10-04 16:08
Should be done in the latest commit.  Please test https://muwire.com/downloads/MuWire-0.8.9-GitHub73-2.zip

**Comment by Searinox** [comment] 2021-10-04 16:27
With regards to responsiveness this does indeed work. All lag is eliminated when tabbed away. I did however notice that if I get my own list it says "Failed 100%" even though it seems to get everything. I'm not sure if this was introduced now. Every other user I tried to download from, it says "Finished 100%". In particular I am trying to see if the final update takes place if you tab back after the download is finished and includes the last files. So far however, it is fine. Although the UI does get stuck during a long update until you tab away - which was to be expected anyway since it's out of this technique's scope - the performance is nonetheless massively improved. A big set of instances of UI lag has been eliminated with this.

**Comment by Searinox** [comment] 2021-10-04 16:31
If you wish to test scaling issues with the download list, there is a user called "muwire" and it is easy to come by them in searches, especially since the network is relatively small at this time. They have a huge file list and I can't count how many files there are but it's surely >100000.

**Comment by zlatinb** [comment] 2021-10-04 16:49
Good to hear.  I don't know why "Failed 100%" is showing, I couldn't reproduce it.  I'm going to close this issue for now, if you discover anything else please reopen.

**Closed by zlatinb** 2021-10-04 16:49 UTC
