### ISSUE TITLE
User Browse File List Filter issue when swapping layouts

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#88] opened 2021-10-14 20:09 UTC
Setting up a filter in Tree view then switching to Table and clearing it or viceversa will result in buggy behavior, which can include still seeing filtered results despite removing the filter, filtered results in one tab but not the other, or an empty list.

**Comment by Searinox** [comment] 2021-10-14 22:04
This is taking a while because I'm trying to reproduce an issue: when the filter is combined in Table mode with Name sorting, I can get the Table mode to remain blank indefinitely - even with a moderate amount of files, to a filtering criteria that outside of aggressive testing otherwise loads fine in a few seconds even combined with name sorting. Do you think you can disable the Clear button while a filtering operation is ongoing and viceversa, disable Filter while clearing is ongoing? One time I managed to make it kill the entire Searches tab wherein I was still able to use and see updates normally in the whole rest of the UI but the Searches tab would remain grayed out even if I tried to search.

**Comment by zlatinb** [comment] 2021-10-14 22:10
The search tab remaining grayed out is because of an exception that must have been thrown on the AWT-EventQueue-0 thread; if that happens the UI is in inconsistent state.

I found a few occasions in which this could happen with the 88 build; you can reproduce it easily if you select a few rows from the table and then filter for something which will give you no results.  I've fixed that in 88-2 https://muwire.com/downloads/MuWire-0.8.9-GitHub88-2.zip

I can disable the clear button while the filtering is happening, that's easy.  Clearing happens on the AWT thread so while clearing goes on you can't interact with the UI anyway.  I'll do that in the next build as it really should be done everywhere there is a filter - the Library, Browse Tab, Search Tab.

**Comment by zlatinb** [comment] 2021-10-16 14:00
Implemented disabling of filter/clear buttons while filtering is ongoing.  Also the filtered results get rendered at rate 30fps in 88-3.

Please try https://muwire.com/downloads/MuWire-0.8.9-GitHub88-3.zip and let me know if this issue is resolved.

**Comment by Searinox** [comment] 2021-10-16 15:32
I don't think I can outright break the Browse List anymore. However I can get the filtering widgets permanently disabled by clicking Filter immediately after clicking Clear. I think the buttons need to also be disabled during a Clearing operation.

**Comment by zlatinb** [comment] 2021-10-16 16:44
I couldn't reproduce this.. do you first click Filter and then Clear or the other way around?  Was the filter field empty?  Clearing happens on the UI thread, so it's not possible to do anything else until it finishes.

I found one case where the buttons may get disabled permanently, and that is fixed in the latest commit.  It would only happen if there are very few results and the filtering finishes before the widgets get disabled, i.e. a race condition.

**Comment by Searinox** [comment] 2021-10-16 17:14
I had text in the filtering field. I clicked Filter. Waited for everything to filter. Hit Clear and as the tree went blank during the clearing I hit Filter again. The buttons and textbox became disabled again as they normally do now when using Filter. But they never came back out of it again, even after the unfiltered tree came back on display.

**Comment by zlatinb** [comment] 2021-10-16 19:11
I reproduced this.  I must have been wrong about the clearing happening on the UI thread.  I'll need to investigate this more thoroughly, at the moment I don't understand exactly what is happening.

**Comment by zlatinb** [comment] 2021-10-16 20:05
Indeed reading the documentation can be a good thing.  All this time I've been wrong about actions being on the UI thread.  Anyway, fixed in 88-4

Also, filtering is now done in parallel using multiple background threads, so it filtered results should show up faster.  Unfortunately the clearing operation has to happen on the UI thread, which means if you're looking at 500k files the UI will just freeze for a while when you press Clear.

https://muwire.com/downloads/MuWire-0.8.9-GitHub88-4.zip

**Comment by Searinox** [comment] 2021-10-16 20:21
Some unresponsiveness in an understandably extreme situation is okay. What isn't okay is the UI seeming responsive and usable when in fact doing so may create inconsistent states and lead to exceptions. This is the better solution. Can confirm it's working. Unless you plan more tests or optimizations you can close this because I can no longer reproduce the issue.

**Comment by zlatinb** [comment] 2021-10-16 20:28
Happy to close this one!

**Comment by Searinox** [comment] 2021-10-17 10:00
~8.4 seconds to clear a filter on a 500000 file list. I personally think it's fine for how big the list is. But I have no comparison to your experience to know just how much you're expecting this to take.

**Comment by Searinox** [comment] 2021-10-17 10:34
Before I say more stupid things again: the above results were with the Table view SORTED. Without sorting this is pretty much instantaneous so surely all the extra time is just the sorting computation.

**Comment by Searinox** [comment] 2021-10-17 12:22
Confirming that all is good. Thank you.

**Comment by zlatinb** [comment] 2021-10-17 12:27
Good to hear.  I'll add it to my long-term TODO list to research if there is any way to do the table sorting async.  But for now, this issue is done for good.

**Closed by zlatinb** 2021-10-17 12:27 UTC
