### ISSUE TITLE
Some Shared Files Missing from Searches

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#67] opened 2021-09-25 15:05 UTC
When sharing files on MuWire's network, not all of them show up in the results. This should be reliable to reproduce by sharing some random files(try around 1000 files of varying sizes and filenames). After a few minutes you should be able to find at least some of them in searches.

However, not all files will show up. Even if being given more than a day, those files simply will not appear in searches. Which files end up not appearing seems to be random. Attempts to unshare everything and then share again results in a different set of files being findable.

They do however appear normally if you get the user's file list. This may or may not be linked to a second issue where attempting to download specifically those unfindable files results in weird download behavior.

**Comment by zlatinb** [comment] 2021-09-25 15:44
I'll try to reproduce.  There are a few places that there could a problem:
1. Generation of shared file descriptor - this doesn't seem to be the case because Browse Host finds the file.
2. Generation of SearchIndex - this is where keyword searches are processed.  Problem is most likely here.
3. Delivery of results over the network - if this is the case, it's an I2P connection issue, but it wouldn't be reproducible.

Here's what you can do without building from source - right-click on a file that you cannot find through search and select "Show File Details".  A small window will appear with 3 tabs - `Search Hits`, `Downloaders`, `Certificates`.  Do you see the search query in the `Search Hits` tab?  Every time a file is returned as a result to someone that is recorded in the File details (but they get cleared at restart).  If it was a search, the keyword should be dssplayed.  If it was Browse Host, an entry with `Browse Host` will be in the table.

**Comment by Searinox** [comment] 2021-09-25 16:06
I performed a search using a file name just now. The search is such that, the machine sharing them, has two versions of that file in the same folder, both with only a very small naming difference that should mean both are found. Let's call them File A and File B.

File A was found, but file B was not.

On the MuWire instance sharing the two files, I went to File B, and checked File Details. In the Search Hits tab, there is a listing with exactly the timestamp of when I made the search. The query also matches what I searched.

I then selected File A and checked File Details. In the Search Hits tab, the same query with the same timestamp appears.

So when I made the search query for the files, both File A and File B were hit, but the search results only displayed File A for some reason.

There are also some Browse Host entries for both File A and B. These relate to some of my earlier attempts, so those were recorded correctly.

**Comment by Searinox** [comment] 2021-09-25 16:12
I went ahead just now and made more checks using some other obscure files. They didn't show up in any of the searches. But on the node sharing them, I was able to find the username, timestamp, and search query that match the searches I just made. There was no search query listed - only Browse Files - before the searches and then after the searches it listed these events as having taken place. So the node making the share detects the search queries every single time even when the one making the search gets no search results, so either the sharing node isn't responding to the search or the searching node isn't getting the response.

**Comment by zlatinb** [comment] 2021-09-25 16:25
Ok, that is somewhat good news, means the bug is not in the search index, but in the transfer of the results from the sharing node to the searching node.  I still haven't been able to reproduce it btw.

Is it possible for you to build from source?  If yes it would make it much easier to track this down.  If not, I can build a special MuWire distribution that enables logging just for you, but it will take me some more time.

**Comment by Searinox** [comment] 2021-09-25 17:38
I cannot build from source unfortunately. Might help to know that I'm behind a NAT with no port forwarding done, but I2P standalone has always worked fine without that.

**Comment by zlatinb** [comment] 2021-09-25 17:51
If you are running I2P standalone then we can still debug without building from source.  Follow these steps on the node sharing the files:

1. Shut down Muwire if it's running
2. Edit `c:\Users\<username>\AppData\Roaming\MuWire\MuWire.properties` and change `embeddedRouter` to `false`
3. Download the .zip distribution from https://muwire.com/downloads/MuWire-0.8.9.zip
4. Start the standalone I2P router, wait until it comes up and connects
5. unzip the `MuWire-0.8.9.zip` somewhere, then launch the `bin\MuWire.bat` file.  If you didn't make any changes to the I2P router MuWire should find it and connect using the external I2P router.

If you get this far and MuWire is working, all that is left is to enable logging:

1. Shut down MuWire
2. Save the following file https://github.com/zlatinb/muwire/blob/master/logging/2_logging.properties as `logging.properties` in the same folder from where you launch `MuWire.bat`
3. Launch `MuWire.bat` again.  A file called `MuWire.log` should appear in the same folder.

Now, try to reproduce the problem and watch for the string "problem sending results" in the `MuWire.log` file.

**Comment by Searinox** [comment] 2021-09-25 18:04
Trying to run muwire.bat:

D:\Program Files\MuWire\bin>muwire.bat
Unrecognized option: --add-opens
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by zlatinb** [comment] 2021-09-25 18:15
I assume you have Java 8?  Can you try and install Java 11 from https://adoptium.net ?  

If you want to go back to regular usage of MuWire, just change the `embeddedRouter` back to `true`.

**Comment by Searinox** [comment] 2021-09-25 19:36
I ran a test.

I ran the zipped distribution via JRE11 as the node that is being searched. I started it up with the logging parameter set.

On the other machine, I ran the MuWire distribution normally. I used that system to perform a search query. The search should've hit a number of results from the JRE11 machine. A few results were indeed found but not all.

Looking to the JRE11 machine, I filtered through the files that had not been found and confirmed that they had indeed gotten a hit. The hit was timestamped to "2021-09-25 18:41". I then opened MuWire.log from the JRE11 instance.

I searched for all the log entries referencing the ID of the user that the search was performed from. Filtering through the log, I found the entries below.

Note: I have anomimized all information I found to be of specific nature. {SEARCHING_ROUTER} is the ID of the machine that performed the search. A number of other values have been redacted out. However, the ones that had identival values were tagged in a unique manner. So even though you may not see the values themselves, you can still tell where there was an identical value or a different one.

There are more log entries inbetween the ones listed here but I filtered them out since they did not seem of relevance. Let me know if you need more.

Log:

2021-09-25 18:40:47.669 WARNING java_util_logging_Logger$log$6 call Hard disconnecting, remove? true on [Connection {CONNECTION}/unknown to {SEARCHING_ROUTER}.b32.i2p up 30s wsize: 1 cwin: 3 rtt: 0 rto: 36000 unacked out: 1 unacked in: 0 sent: 1 rcvd: 0 ackThru -1 ssThresh 2 minRTT 2147483647 maxWin 128 MTU 1812] 
java.lang.Exception: cause
	at net.i2p.client.streaming.impl.Connection.disconnect(Connection.java:785)
	at net.i2p.client.streaming.impl.Connection.disconnect(Connection.java:739)
	at net.i2p.client.streaming.impl.Connection.waitForConnect(Connection.java:1224)
	at net.i2p.client.streaming.impl.ConnectionManager.connect(ConnectionManager.java:552)
	at net.i2p.client.streaming.impl.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:588)
	at net.i2p.client.streaming.impl.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:648)
	at net.i2p.client.streaming.I2PSocketManager$connect$2.call(Unknown Source)
	at com.muwire.core.connection.I2PConnector.connect(I2PConnector.groovy:17)
	at com.muwire.core.connection.I2PConnector$connect.call(Unknown Source)
	at com.muwire.core.connection.ConnectionEstablisher.connect(ConnectionEstablisher.groovy:93)
	at jdk.internal.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at com.muwire.core.connection.ConnectionEstablisher$_connectIfNeeded_closure4.doCall(ConnectionEstablisher.groovy:85)
	at com.muwire.core.connection.ConnectionEstablisher$_connectIfNeeded_closure4.doCall(ConnectionEstablisher.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

2021-09-25 18:40:47.669 WARNING org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite doInvoke Couldn't connect to {SEARCHING_ROUTER}.b32.i2p 
java.net.NoRouteToHostException: Connection timed out
	at net.i2p.client.streaming.impl.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:595)
	at net.i2p.client.streaming.impl.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:648)
	at net.i2p.client.streaming.I2PSocketManager$connect$2.call(Unknown Source)
	at com.muwire.core.connection.I2PConnector.connect(I2PConnector.groovy:17)
	at com.muwire.core.connection.I2PConnector$connect.call(Unknown Source)
	at com.muwire.core.connection.ConnectionEstablisher.connect(ConnectionEstablisher.groovy:93)
	at jdk.internal.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at com.muwire.core.connection.ConnectionEstablisher$_connectIfNeeded_closure4.doCall(ConnectionEstablisher.groovy:85)
	at com.muwire.core.connection.ConnectionEstablisher$_connectIfNeeded_closure4.doCall(ConnectionEstablisher.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

2021-09-25 18:41:12.669 WARNING java_util_logging_Logger$log$4 call 7283: Send failed (cause: 3) [MessageId: 29357716] to {SEARCHING_ROUTER}.b32.i2p out OB client {ID8}: GW {ID6} ElG:me.{VALUE11}-->{ID3} ElG:{VALUE7}-->{ID1} EC:{VALUE8}-->{ID2} EC:{VALUE9} exp. Sat Sep 25 18:45:25 GMT 2021 replyMsgID 775872503 with 378/61440 msgs/bytes in [Lease: 
	End Date: Sep 25, 2021, 9:42 PM
	Gateway: [Hash: {GATEWAY_HASH}]
	TunnelId: 3164180219] ack IB client {ID8}: GW {GATEWAY} ElG:{VALUE14}-->{ID4} EC:{VALUE3}-->{ID5} EC:{VALUE4}-->{ID6} ElG:{VALUE13}.me exp. Sat Sep 25 18:46:08 GMT 2021 replyMsgID 1685112579 with 288/294912 msgs/bytes after 55001ms  

2021-09-25 18:41:21.671 WARNING java_util_logging_Logger$log$4 call 7640: Send failed (cause: 3) [MessageId: 29357817] to {SEARCHING_ROUTER}.b32.i2p out OB client {ID8}: GW {ID6} ElG:me.{VALUE11}-->{ID3} ElG:{VALUE7}-->{ID1} EC:{VALUE8}-->{ID2} EC:{VALUE9} exp. Sat Sep 25 18:45:25 GMT 2021 replyMsgID 775872503 with 388/62464 msgs/bytes in [Lease: 
	End Date: Sep 25, 2021, 9:42 PM
	Gateway: [Hash: {GATEWAY_HASH}]
	TunnelId: 3164180219] ack IB client {ID8}: GW {GATEWAY} ElG:{VALUE14}-->{ID4} EC:{VALUE3}-->{ID5} EC:{VALUE4}-->{ID6} ElG:{VALUE13}.me exp. Sat Sep 25 18:46:08 GMT 2021 replyMsgID 1685112579 with 296/303104 msgs/bytes after 55001ms  

2021-09-25 18:41:21.671 WARNING java_util_logging_Logger$log$4 call Rcvd soft failure status 3 for msg 202 on [Connection {CONNECTION}/unknown to {SEARCHING_ROUTER}.b32.i2p up 64s wsize: 1 cwin: 3 rtt: 0 rto: 36000 unacked out: 0 unacked in: 0 sent: 1 rcvd: 0 ackThru -1 ssThresh 2 minRTT 2147483647 maxWin 128 MTU 1812]  

2021-09-25 18:41:39.672 WARNING java_util_logging_Logger$log$4 call 8442: Send failed (cause: 3) [MessageId: 29358019] to {SEARCHING_ROUTER}.b32.i2p out OB client {ID8}: GW {ID6} ElG:me.{VALUE11}-->{ID3} ElG:{VALUE7}-->{ID1} EC:{VALUE8}-->{ID2} EC:{VALUE9} exp. Sat Sep 25 18:45:25 GMT 2021 replyMsgID 775872503 with 411/75776 msgs/bytes in [Lease: 
	End Date: Sep 25, 2021, 9:42 PM
	Gateway: [Hash: {GATEWAY_HASH}]
	TunnelId: 3164180219] ack IB client {ID8}: GW {GATEWAY} ElG:{VALUE10}-->{ID7} EC:{VALUE5}-->{ID5} EC:{VALUE6}-->{ID6} ElG:{VALUE12}.me exp. Sat Sep 25 18:49:40 GMT 2021 replyMsgID 3417915108 with 70/71680 msgs/bytes after 55000ms  

2021-09-25 18:41:39.672 WARNING java_util_logging_Logger$log$4 call Rcvd soft failure status 3 for msg 217 on [Connection {CONNECTION}/unknown to {SEARCHING_ROUTER}.b32.i2p up 82s wsize: 1 cwin: 3 rtt: 0 rto: 36000 unacked out: 0 unacked in: 0 sent: 1 rcvd: 0 ackThru -1 ssThresh 2 minRTT 2147483647 maxWin 128 MTU 1812]  
2021-09-25 18:41:40.861 WARNING java_util_logging_Logger$log$4 call Reset received on [Connection {VALUE1}/{VALUE2} to {SEARCHING_ROUTER}.b32.i2p up 2615ms wsize: 3 cwin: 2 rtt: 1327 rto: 1990 unacked out: 2 unacked in: 0 close sent 1278ms ago sent: 3 rcvd: 1 ackThru 0 ssThresh 64 minRTT 1327 maxWin 128 MTU 1812]

**Comment by zlatinb** [comment] 2021-09-25 19:54
Thanks, glad you got the logging working :)

There is a lot of informatio here, and it seems like it's all I2P-level problems.  Let's make some changes to the `logging.properties` file to narrow down the issue.

1. find the line that starts with `.level= WARNING` and change that to `.level= SEVERE`.  Should be line 29.  Don't forget the leading dot `.`
2. At the bottom of the file, add the following line:
```
com.muwire.core.search.ResultsSender.level=INFO
```
3. Restart MuWire and perform a single search for a file that is on the sharing node.  You should see an entry like this in MuWire.log:
```
[timestamp] INFO Sending N resutls for uuid asdf-1234-asdf-1234 to {host.b32.i2p} oobInfohash: true
```

See if the number of results that are being sent according to the log matches the number of results that the searching node receives.  If yes, there is no problem with the I2P connection, and we need to look elsewhere.

Also keep an eye out for any WARNING entires in the log.  There should be much fewer than before, but if there are any they would be relevant specifically to the result delivery.

**Comment by Searinox** [comment] 2021-09-27 20:35
I performed a search that should have returned 3 results on the searching instance. I know it was supposed to be 3 because I filtered what I was sharing with the instance that was searched. 3 files were listed. The search was performed at 23:24. I already had the log open. In the log a single line was added:

2021-09-27 20:24:48.774 INFO org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite doInvoke Sending 3 results for uuid {ID} to {SEARCHING_NODE}.b32.i2p oobInfohash : true

The files also showed up as hit by the search in the Library.

It is starting to look to me like it isn't a problem with hitting searches and responding, rather a problem on the searching instance's side about listing what it finds.

In another search, I entered a term I knew would get lots of hits. I checked the log again. This time it said "sending 278 results .......". But only around 50 results were received, and NONE of them included files from my node. I waited. After exactly 30 seconds from that entry - an interval I'd assume is some manner of timeout - this entry appeared:

2021-09-27 20:30:58.018 WARNING java_util_logging_Logger$log$7 call problem sending results 
java.net.NoRouteToHostException: Connection timed out
	at net.i2p.client.streaming.impl.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:595)
	at net.i2p.client.streaming.impl.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:648)
	at net.i2p.client.streaming.I2PSocketManager$connect$3.call(Unknown Source)
	at com.muwire.core.connection.I2PConnector.connect(I2PConnector.groovy:17)
	at com.muwire.core.connection.I2PConnector$connect$0.call(Unknown Source)
	at com.muwire.core.search.ResultsSender$ResultSendJob.run(ResultsSender.groovy:146)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Searinox** [comment] 2021-09-27 20:41
I do not believe partial search results are the same problem as those that fail to send altogether. I tried the search that returns 200+ results again and again and eventually my results got through.

The specific files in incomplete searches by contrast, NEVER, ever, show up in results. No matter how many times I repeat the search and get the results to show up with no send errors in the log and the correct number of listings, they simply do not appear.

**Comment by Searinox** [comment] 2021-09-27 21:04
Furthermore I have had instances of searches where the same Sender is listed multiple times. I have the search result listing set to sort by file instead of by user. I could not vouch for other users but in my case, the instance from which I'm sharing was never restarted, my internet connection wasn't restarted, and I don't understand why my Sender instance is appearing several times for the same file.

**Comment by zlatinb** [comment] 2021-09-28 05:10
You are right that results should be sent in one chunk, and either all should arrive or none should arrive.  If none arrive then there was a problem establishing the I2P connection and a retry should eventually succeed.

By default, MuWire will not show any results that are already present as shared files on the searching node.  Make sure that the `Options -> GUI -> Exclude local files from results` checkbox is not checked.

The sender appearing multiple times when results are grouped by file is a bug in the UI.  If there the same file is shared more than once (possibly under different name) then when displayed the sender will appear as many times as the file was shared.  It needs to get fixed, but it's unrelated to the missing results issue.

**Comment by Searinox** [comment] 2021-09-28 09:45
I believe that has fixed it!

I am no longer able to reproduce the issue with any files. The setting is reasonable and intuitive and I don't think it needs any changing. I was simply misusing it.

That said, I want to return to my initial post where I outlined a suspicion of a link between this issue and a download that disappears after obtaining the hash. That issue is STILL occurring and now that we understand which files were missing, I am going to update my assessment of that issue: if a file that is also being shared is attempted to download from another host, the download task disappears after the hash is obtained, but the download is still there and will resume when MuWire is restarted.

If you believe there are any more unanswered questions on the issue of missing files, I will leave it at your discretion to keep the issue open or close it. Personally, I don't think there are any problems and this can be closed.

**Comment by zlatinb** [comment] 2021-09-28 09:55
Glad to hear.  The discussion here has brought several issues that need addressing, some are known some are new.  I'll close this issue but before that I will add to the list of issue on #66 :

* Apostrophy not escaped correctly in search result display
* Multiple identical files result in the same sender listed multiple times
* Downloading of files that are already present isn't working - I see you opened #68

**Closed by zlatinb** 2021-09-28 09:55 UTC
