### ISSUE TITLE
Can't share anything: error 500 NullPointerException

### ISSUE THREAD

**Issue by etam** [zlatinb/muwire#39] opened 2020-02-23 16:52 UTC
Version: 0.6.9-b0 plugin

This is what I get every time I try to share anything:
```
HTTP ERROR 500

Problem accessing /MuWire/Files. Reason:

    Server Error

Caused by:

java.lang.NullPointerException
	at com.muwire.webui.FilesServlet.doPost(FilesServlet.java:151)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:529)
	at net.i2p.router.web.HostCheckHandler.handle(HostCheckHandler.java:118)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)

Powered by Jetty:// 
```

What's interesting, I have 2 i2p nodes and this happens only on one of them.

**Comment by zlatinb** [comment] 2020-02-23 16:55
The way the plugin works is that you need to enter a filesystem path on the machine the plugin is running on and then press share.  That is relevant if the plugin is running on a machine different than the browser; at the moment there is no way to share files on the machine the browser is running.

What happens on the other i2p node, the one that doesn't throw the exception?

**Comment by zlatinb** [comment] 2020-02-23 16:56
Hmm, on a second looks like the plugin isn't correctly initialized.  If that's the case a simple plugin restart should get rid of the issue.  Let me know if that helps

**Comment by etam** [comment] 2020-02-23 17:00
> The way the plugin works is that you need to enter a filesystem path on the machine the plugin is running on and then press share. That is relevant if the plugin is running on a machine different than the browser; at the moment there is no way to share files on the machine the browser is running.

I'm well aware of that.

> Hmm, on a second looks like the plugin isn't correctly initialized. If that's the case a simple plugin restart should get rid of the issue. Let me know if that helps.

I noticed. When I tried to search for anything I got error

```
HTTP ERROR 403

Problem accessing /MuWire/Search. Reason:

    Not initialized

Powered by Jetty:// 
```

Restarting plugin helped.

**Comment by zlatinb** [comment] 2020-02-23 17:05
Glad it worked.  I'm not sure why initialization sometimes fails, will raise the issue with the I2P devs.  I suspect it might be an I2P issue.  Will leave ticket open until I find out more

**Comment by zlatinb** [comment] 2020-02-23 18:40
@etam plugin 0.6.10-b1 is up on muwire.i2p with some changes that should fix the race condition that I believe is causing the mis-initialization.  Also bumps the core to version 0.6.10 which fixes persistence of file comments.  Would appreciate if you can give it a try on your routers.

**Comment by etam** [comment] 2020-02-23 19:02
0.6.10-b0 was fine, but with 0.6.10-b1 I get constant `MuWire is initializing, please wait…` on both nodes.

**Comment by zlatinb** [comment] 2020-02-23 19:19
I can't reproduce this.  Are you trying a clean install or an upgrade?

**Comment by etam** [comment] 2020-02-23 20:03
upgrade

**Comment by zlatinb** [comment] 2020-02-23 20:05
Does restarting the entire I2P router help?  I suspect something probably didn't shut down cleanly from -b0 and is still lingering.

**Comment by etam** [comment] 2020-02-23 20:40
restarting whole i2p router helps

**Comment by zlatinb** [comment] 2020-03-13 13:38
Found what was causing the indefinite "MuWire is initializing, please wait" message - a strange exception probably to do with the pack200 compression of the default properties file included inside the jar.

Fixed in 0.6.11-b33, would appreciate if you give it a try.

**Comment by etam** [comment] 2020-03-13 14:34
Well, the issue happened only when updating from 0.6.10-b0 to 0.6.10-b1 without restarting i2p router. I restarted router and since then everything worked fine. So now I can only test if it's not broken going forward.

**Comment by etam** [comment] 2020-03-13 14:58
updating from 0.6.10-b1 to 0.6.11-b33 without restarting i2p router works fine.

**Comment by zlatinb** [comment] 2020-03-13 15:18
Thanks.  I'll leave the issue open for a few days and if the original problem doesn't occur again I'll close it.

**Closed** 2020-03-19 14:36 UTC
